/**
 * Stock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Stock model module.
* @module model/Stock
* @version v1
*/
export default class Stock {
    /**
    * Constructs a new <code>Stock</code>.
    * Stock info
    * @alias module:model/Stock
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Stock</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Stock} obj Optional instance to populate.
    * @return {module:model/Stock} The populated <code>Stock</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Stock();

            
            
            

            if (data.hasOwnProperty('stockId')) {
                obj['stockId'] = ApiClient.convertToType(data['stockId'], 'String');
            }
            if (data.hasOwnProperty('exchangeId')) {
                obj['exchangeId'] = ApiClient.convertToType(data['exchangeId'], 'String');
            }
            if (data.hasOwnProperty('stockCode')) {
                obj['stockCode'] = ApiClient.convertToType(data['stockCode'], 'String');
            }
            if (data.hasOwnProperty('stockNameCN')) {
                obj['stockNameCN'] = ApiClient.convertToType(data['stockNameCN'], 'String');
            }
            if (data.hasOwnProperty('launchDate')) {
                obj['launchDate'] = ApiClient.convertToType(data['launchDate'], 'Date');
            }
            if (data.hasOwnProperty('websiteUrl')) {
                obj['websiteUrl'] = ApiClient.convertToType(data['websiteUrl'], 'String');
            }
            if (data.hasOwnProperty('industryName')) {
                obj['industryName'] = ApiClient.convertToType(data['industryName'], 'String');
            }
            if (data.hasOwnProperty('cityNameCN')) {
                obj['cityNameCN'] = ApiClient.convertToType(data['cityNameCN'], 'String');
            }
            if (data.hasOwnProperty('provinceNameCN')) {
                obj['provinceNameCN'] = ApiClient.convertToType(data['provinceNameCN'], 'String');
            }
        }
        return obj;
    }

    /**
    * Stock id
    * @member {String} stockId
    */
    stockId = undefined;
    /**
    * Exchange id
    * @member {String} exchangeId
    */
    exchangeId = undefined;
    /**
    * Stock code
    * @member {String} stockCode
    */
    stockCode = undefined;
    /**
    * Stock name cn
    * @member {String} stockNameCN
    */
    stockNameCN = undefined;
    /**
    * Launch date
    * @member {Date} launchDate
    */
    launchDate = undefined;
    /**
    * Website url
    * @member {String} websiteUrl
    */
    websiteUrl = undefined;
    /**
    * Industry name
    * @member {String} industryName
    */
    industryName = undefined;
    /**
    * City name cn
    * @member {String} cityNameCN
    */
    cityNameCN = undefined;
    /**
    * Province name cn
    * @member {String} provinceNameCN
    */
    provinceNameCN = undefined;








}


