// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Stock

    Schemes:
      http
    Host: localhost
    BasePath: /api/stock/v1
    Version: v1
    Contact: mars

    Consumes:
    - application/json;charset=utf-8

    Produces:
    - application/json;charset=utf-8

swagger:meta
*/
package restapi
