// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Stock",
    "contact": {
      "name": "mars"
    },
    "version": "v1"
  },
  "basePath": "/api/stock/v1",
  "paths": {
    "/stocks": {
      "get": {
        "summary": "Get stock list",
        "operationId": "StocksList",
        "parameters": [
          {
            "type": "string",
            "description": "Exchange id.eg sz,sh...",
            "name": "exchangeId",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Stock list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Stock"
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Internal error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/stocks/{stockId}": {
      "get": {
        "summary": "Get stock,sh_{code},sz_{code}",
        "operationId": "StocksGet",
        "parameters": [
          {
            "type": "string",
            "description": "Stock id",
            "name": "stockId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Stock",
            "schema": {
              "$ref": "#/definitions/Stock"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Internal error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Stock": {
      "id": "Stock",
      "description": "Stock info",
      "type": "object",
      "required": [
        "stockId",
        "exchangeId"
      ],
      "properties": {
        "exchangeId": {
          "description": "Exchange id",
          "type": "string"
        },
        "stockId": {
          "description": "Stock id",
          "type": "string"
        }
      }
    }
  }
}`))
}
