// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/Stock/api/models"
)

// StocksListOKCode is the HTTP code returned for type StocksListOK
const StocksListOKCode int = 200

/*StocksListOK Stock list

swagger:response stocksListOK
*/
type StocksListOK struct {

	/*
	  In: Body
	*/
	Payload models.StocksListOKBody `json:"body,omitempty"`
}

// NewStocksListOK creates StocksListOK with default headers values
func NewStocksListOK() *StocksListOK {
	return &StocksListOK{}
}

// WithPayload adds the payload to the stocks list o k response
func (o *StocksListOK) WithPayload(payload models.StocksListOKBody) *StocksListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stocks list o k response
func (o *StocksListOK) SetPayload(payload models.StocksListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StocksListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.StocksListOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// StocksListBadRequestCode is the HTTP code returned for type StocksListBadRequest
const StocksListBadRequestCode int = 400

/*StocksListBadRequest Bad request

swagger:response stocksListBadRequest
*/
type StocksListBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewStocksListBadRequest creates StocksListBadRequest with default headers values
func NewStocksListBadRequest() *StocksListBadRequest {
	return &StocksListBadRequest{}
}

// WithPayload adds the payload to the stocks list bad request response
func (o *StocksListBadRequest) WithPayload(payload string) *StocksListBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stocks list bad request response
func (o *StocksListBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StocksListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// StocksListInternalServerErrorCode is the HTTP code returned for type StocksListInternalServerError
const StocksListInternalServerErrorCode int = 500

/*StocksListInternalServerError Internal error

swagger:response stocksListInternalServerError
*/
type StocksListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewStocksListInternalServerError creates StocksListInternalServerError with default headers values
func NewStocksListInternalServerError() *StocksListInternalServerError {
	return &StocksListInternalServerError{}
}

// WithPayload adds the payload to the stocks list internal server error response
func (o *StocksListInternalServerError) WithPayload(payload string) *StocksListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stocks list internal server error response
func (o *StocksListInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StocksListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
