/**
 * Stock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Stock);
  }
}(this, function(expect, Stock) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Stock.Stock();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Stock', function() {
    it('should create an instance of Stock', function() {
      // uncomment below and update the code to test Stock
      //var instane = new Stock.Stock();
      //expect(instance).to.be.a(Stock.Stock);
    });

    it('should have the property stockId (base name: "stockId")', function() {
      // uncomment below and update the code to test the property stockId
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property exchangeId (base name: "exchangeId")', function() {
      // uncomment below and update the code to test the property exchangeId
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property stockCode (base name: "stockCode")', function() {
      // uncomment below and update the code to test the property stockCode
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property stockNameCN (base name: "stockNameCN")', function() {
      // uncomment below and update the code to test the property stockNameCN
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property launchDate (base name: "launchDate")', function() {
      // uncomment below and update the code to test the property launchDate
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property websiteUrl (base name: "websiteUrl")', function() {
      // uncomment below and update the code to test the property websiteUrl
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property industryName (base name: "industryName")', function() {
      // uncomment below and update the code to test the property industryName
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property cityNameCN (base name: "cityNameCN")', function() {
      // uncomment below and update the code to test the property cityNameCN
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

    it('should have the property provinceNameCN (base name: "provinceNameCN")', function() {
      // uncomment below and update the code to test the property provinceNameCN
      //var instane = new Stock.Stock();
      //expect(instance).to.be();
    });

  });

}));
